version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  name: latest-build.zip  # Ensures the same artifact name every time
  discard-paths: yes
  base-directory: build  # Directory with output files (e.g., React app)
